version: "3.9"

services:
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: ${PORT}
      SECRET: ${SECRET}
    ports:
      - "${PORT}:${PORT}"
    restart: always

volumes:
  mysql_data:
